### ISSUE TITLE
Add ability to use Windows authentication for connecting to SQL database

### ISSUE THREAD

**Issue by clayschick** [sanagama/vscode-mssql#1]

**Comment by sanagama** [comment]
Thanks for the feedback. I'll put this request on my backlog and address it after fixing a few other bugs that were reported.

**Comment by lw-schick** [comment]
i miss that feature too... in our company we only work with trusted authentications....

**Comment by ONeville** [comment]
Will be helpful to allow the Windows authentication.

**Comment by srinath29** [comment]
Any update with it ? Please, I am waiting for this feature.

**Comment by KaelD** [comment]
Looks like support for this has been added to node-mssql, it just needs to be implemented here. https://github.com/patriksimek/node-mssql/commit/cc1ebe78f00f257e13a06bd8970c04274a27536e#diff-04c6e90faac2675aa89e2176d2eec7d8R286

**Comment by sanagama** [comment]
Thanks for your feedback everyone.

We announced Microsoft's official 'mssql' extension for VS Code at Connect(); today. Here's a link: [mssql extension](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql)

I have copied this issue over to [https://github.com/Microsoft/vscode-mssql/issues/356](https://github.com/Microsoft/vscode-mssql/issues/356) and closed this one.

Regards,
Sanjay
