### ISSUE TITLE
VSCode-mssql not accepting hostname\instancename format

### ISSUE THREAD

**Issue by MaximoTrinidad** [sanagama/vscode-mssql#12]
I'm not successful in making it work to execute against "hostname/instancename" format.  Or, I'm not sure how to make it work.

I've tried:
"server": "MTRINIDADLT2\MSSQL2K16A",
"server": "MTRINIDADLT2\MSSQL2K16A",
"server": "'MTRINIDADLT2\MSSQL2K16A'",

Windows 10 build 14391
VS Code version 1.5.3

![vscodesql_err_2016-09-30](https://cloud.githubusercontent.com/assets/19892435/19007619/ddd5c3e0-8733-11e6-8c74-909c1fe489c3.jpg)

**Comment by sanagama** [comment]
Thx for reporting this, I'll take a look. Meanwhile, can you try escaping the '\' and see if that works?
Example: "server": "MTRINIDADLT2\MSSQL2K16A"

**Comment by MaximoTrinidad** [comment]
No! I show all samples that I tried and didnt work on the incident.

:)

Get Outlook for Androidhttps://aka.ms/ghei36

On Tue, Oct 4, 2016 at 1:22 PM -0400, "Sanjay Nagamangalam" <notifications@github.com<mailto:notifications@github.com>> wrote:

Thx for reporting this, I'll take a look. Meanwhile, can you try escaping the '\' and see if that works?
Example: "server": "MTRINIDADLT2\MSSQL2K16A"

##

**Comment by sanagama** [comment]
Sorry Maximo, I had a typo in my response. Can you try this (2 backslashes between host and instance):
"server": "MTRINIDADLT2\MSSQL2K16A"

**Comment by MaximoTrinidad** [comment]
Sorry!  My mistake to.  In the initial sample I meant to say that I tried:
"server": "MTRINIDADLT2\MSSQL2K16A",
"server": "MTRINIDADLT2//MSSQL2K16A",

Unless, it doesn't work with SQL Server 2016?

![vscode-mssql_err_2016-10-05_](https://cloud.githubusercontent.com/assets/19892435/19130654/123a216e-8b1a-11e6-89cb-1bed452b0fc7.jpg)

**Comment by MaximoTrinidad** [comment]
I create another instance in another machine to make sure I'm getting the error.  
Any tip is welcome! 
:)

![vscodemsqlerr](https://cloud.githubusercontent.com/assets/19892435/19154784/e749071e-8ba9-11e6-82be-d7648e828bf8.png)

**Comment by hmendozap** [comment]
Unfortunately I'm getting a similar error when connecting to a SQL 2016 Instance. Any Idea why that may happen or how to debug it?

Thanks,
HM

**Comment by MaximoTrinidad** [comment]
Oops!!  No is worst.  I did uninstall/reinstall again the extension and now not even the single instance works.  

This is on VS Code version 1.6.1

Now, I'm getting a warning to add connections when is already loaded.

:(

![vscode-mssql01_10272016](https://cloud.githubusercontent.com/assets/19892435/19774758/21274656-9c3c-11e6-9492-78b857dcc2d0.jpg)

**Comment by sanagama** [comment]
Hi Maximo,

Thanks for your feedback. This is addressed in Microsoft's official 'mssql' extension for VS Code that we announced at Connect(); today. Here's a link: [mssql extension](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql)

Please can you try this and open an issue if you are still having problems: https://github.com/Microsoft/vscode-mssql/issues

Regards,
Sanjay

**Comment by MaximoTrinidad** [comment]
Hey @sanagama,  Thanks for all the effort.  I have use the new Microsoft mssql extension and is working fine with the Servername\SQLinstance.

Thanks again,
Maximo

**Comment by hmendozap** [comment]
Thanks @sanagama  for the effort!
