### ISSUE TITLE
Messages tab not showing infomessage print statement output or errors with severity of 10 or lower

### ISSUE THREAD

**Issue by BretStateham** [sanagama/vscode-mssql#13]
The following statements

`PRINT N'This is an informational message';`
and

`RAISERROR (N'This is an informational message',10,1);`

Do not show up on the "Messages" tab. 

If you raise the severity of the `RAISERROR` to 11, it does show, but looks like an error, not an info  message.

`RAISERROR (N'This is an informational message, but looks like an error because the severity is above 10',11,1);`

Not sure if this is a limitation of the underlying connection or not. 

Bret

**Comment by sanagama** [comment]
Thanks for your feedback. This is addressed in Microsoft's official 'mssql' extension for VS Code that we announced at Connect(); today. Link: [mssql extension](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql)
