### ISSUE TITLE
Add ability to export data to a file

### ISSUE THREAD

**Issue by Chrisboh** [sanagama/vscode-mssql#14]
So I needed to share out the results of a query today and was unable to find a way to get all of the data into a format I could send to someone.  It would be ideal if I could export it to a file so I could send it out to other people.

**Comment by sanagama** [comment]
Thanks for your feedback. This is addressed in Microsoft's official 'mssql' extension for VS Code that we announced at Connect(); today. Link: [mssql](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql)
