### ISSUE TITLE
Doesn't remember SQL connection info

### ISSUE THREAD

**Issue by AllPinkyNoBrain** [sanagama/vscode-mssql#2]
"Remembers the connection in the list of recently used connections upon a successful connection."
Nope. I have to type servername/dbname/user/pwd every single time, and can't see any way/where that it's stored/remembered, making this extension unusable.
Shame, because VSCode is rapidly becoming my go-to for everything....

**Comment by sanagama** [comment]
Thanks for trying the extension and providing feedback. I have some questions to help me fix the issues you're running into:
1. After connecting to a database, do you see the connection list of recent connections when you press Ctrl+Shift+P to show the command palette and choose "MSSQL: Connect to a database"? The recent connections should be in a picklist right below "New Connection...". If you don't see this then you've found a bug that I will need to repro & fix.
2. At the moment, the extension clears out the list of recent connections when you exit VS Code, so recent connections are not saved across multiple launches of VS Code. I can change behaviour if this helps address your scenario.
3. As of right now, the extension does not save the password along with the recent connections and prompts you to enter the password each time you click on a recent connection from the picklist. I can change this behaviour if this helps address your scenario.

Please let me know. I can make these changes and publish an update on the gallery.

Regards,
Sanjay

**Comment by AllPinkyNoBrain** [comment]
Hi Sanjay

Thanks for getting back to me so quickly.
1. Yes, I see what is the existing connection, if I launch the command palette and type “mssql”. However, I get a warning message (telling me that I have to open a .sql file to perform the command - screen grab attached) if I have anything selected/highlighted in a .sql file that’s already open (if that makes sense).
2. Persist across multiple launches - yes please! I connect to our LAN via a VPN, I’m working on a Mac, and my server names are like this: “VM-AAA-BBB-CCC.long.domain.name.local”. So, typing that, a db name, user and password every time I connect (more than once every day) means my coffee goes cold while I type!
3. Saving the password would also be a massive help, but it’s not the most important thing. I guess it’s good to remember passwords, otherwise I’d have to have them written down somewhere (oh, wait).

I’ve only just started with VS Code, but I already love the fact that extensions like yours make it a one-stop editor.

## 

Kevin

On 25 May 2016 at 03:18:25, Sanjay Nagamangalam (notifications@github.commailto:notifications@github.com) wrote:

Thanks for trying the extension and providing feedback. I have some questions to help me fix the issues you're running into:
1. After connecting to a database, do you see the connection list of recent connections when you press Ctrl+Shift+P to show the command palette and choose "MSSQL: Connect to a database"? The recent connections should be in a picklist right below "New Connection...". If you don't see this then you've found a bug that I will need to repro & fix.
2. At the moment, the extension clears out the list of recent connections when you exit VS Code, so recent connections are not saved across multiple launches of VS Code. I can change behaviour if this helps address your scenario.
3. As of right now, the extension does not save the password along with the recent connections and prompts you to enter the password each time you click on a recent connection from the picklist. I can change this behaviour if this helps address your scenario.

Please let me know. I can make these changes and publish an update on the gallery.

Regards,
Sanjay

**Comment by sanagama** [comment]
Thx for the details Kevin. I'll work on addressing these issues over the weekend. Please can you send me an e-mail at sanagama2 -at- gmail -dot- com with the screen grab? I'll reply back with a private .vsix with the fixes that you can side-load into VS Code to see if these issues are addressed. After that, I'll publish an update to the gallery.

**Comment by sanagama** [comment]
Fixed in 0.0.3: added support to load connection picklist from VS Code user settings.
