### ISSUE TITLE
Two issues with the initial load of VS code

### ISSUE THREAD

**Issue by asadsahi** [sanagama/vscode-mssql#4]
When VS code is opened with vscode-mssql extension installed, 

1) it opens the output windows of MSSQL always. 
2) It shows MSSQL twice in output window dropdown.

![image](https://cloud.githubusercontent.com/assets/3470892/15815537/ab1273fa-2bc5-11e6-830d-5150b9665f7e.png)

**Comment by sanagama** [comment]
Version 0.0.3 of the extension does not show the welcome message on extension load since a few users complained. Can you install the latest version and check if this still happens?

**Comment by asadsahi** [comment]
Thanks, seems to be fixed in latest version.
