### ISSUE TITLE
Show/switch active database

### ISSUE THREAD

**Issue by aharpervc** [sanagama/vscode-mssql#5]
Right now it's not clear what database the current file will execute on, or on a results panel, what database the results are for. This should be added to the UI. 

Additionally, there should be a UI for switching active databases (like the menu in SSMS).

**Comment by sanagama** [comment]
Hi, thanks for your feedback. Both are good suggestions and I'll add them to my backlog.

**Comment by sanagama** [comment]
Hi, This is addressed in Microsoft's official 'mssql' extension for VS Code that we announced at Connect(); today. Here's a link: [mssql extension](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql)

Please can you try this and open an issue if you are still having problems: https://github.com/Microsoft/vscode-mssql/issues

Regards,
Sanjay
