### ISSUE TITLE
Connecting to another port

### ISSUE THREAD

**Issue by eternalbard** [sanagama/vscode-mssql#6]
I can't connect to a different SQL Server port. With ':Port' or ',Port' it always try to connect to 'MSSQLAddress:1433', like 'MSSQLAddress,1000:1433' or 'MSSQLAddress,1000:1433'.

Is there a way or is something missing?

**Comment by usoluyun** [comment]
same issues. How can I specify a different port?

**Comment by sanagama** [comment]
Hi, thanks for your feedback. I'll work on supporting a user-specified port and release an update this week.

**Comment by sanagama** [comment]
Hi, support to optionally specify a port has been added to version 0.0.4 of the extension published on the VS Code marketplace. Please update the extension and let me know if this works for you. Here's an example of how you can optionally specify a custom port in the connection setting:

``` javascript
{
    "vscode-mssql.connections":
    [
        {
            "server": "mytestserver1",
            "database": "mytestdatabase",
            "user": "sanagama",
            "port": 8181
        }
    ]
}
```
