### ISSUE TITLE
Save Query Output

### ISSUE THREAD

**Issue by maurice1408** [sanagama/vscode-mssql#8]
Would be nice to be able to save the output from a query? Copy / pasting only seems to work against one page of output?

**Comment by sanagama** [comment]
Hi Maurice,

Thanks for your feedback. This is addressed in Microsoft's official 'mssql' extension for VS Code that we announced at Connect(); today. Here's a link: [mssql extension](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql)

Please can you try this and open an issue if you are still having problems: https://github.com/Microsoft/vscode-mssql/issues

Regards,
Sanjay
